// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Journals_And_Domains : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Journals_And_Domains));
        
        string IMigrationMetadata.Id
        {
            get { return "201804182149422_Journals_And_Domains"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
